# This is a basic workflow to help you get started with Actions

name: TestWF

# Controls when the action will run. 
on: pull_request
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      
      - name: Authenticate DevHub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SBX_JWT_SECRET_KEY }}
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SBX_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SBX_USERNAME}} 
        

      - name: Validate with Target Org
        env:
          sbx_username: ${{secrets.SBX_USERNAME}}  
        run: node_modules/sfdx-cli/bin/run force:source:deploy --checkonly --wait 2 -x manifest/package.xml  -u "$sbx_username"
